#!/bin/sh
CACHE="/tmp/kernelv"
[ -f "$CACHE" ] || kernelv -a > "$CACHE"
case $BLOCK_BUTTON in
    1)
        notify-send -i "none" -a "kernel list"\
            "$(cat "$CACHE" || kernelv -a)"
    ;;
    2) [ -f "$CACHE" ] && {
        rm "$CACHE" && kernelv -a > "$CACHE"
       }
    ;;
esac

ICON=""
# THEMED_ICON="<span color='#1793d1'>$ICON</span>"
VALUE="$(uname -r | cut -d '-' -f 1)"
OUTPUT=" $ICON $VALUE "

# underline="underline='single' underline_color='#458588'"
printf "<span color='#83a598' background='#076678' weight='bold'>%s</span>\n" "$OUTPUT"
