#!/bin/sh

VALUE="$(gawk '
/^MemTotal:/ { total=$2 }
/^MemFree:/  { free=$2 }
/^Buffers:/  { free+=$2 }
/^Cached:/   { free+=$2 }
END { printf("%.1f\n", (total-free)/1024/1024) }' /proc/meminfo)"

ICON=""
OUTPUT=" $ICON ${VALUE}GiB "

# underline="underline='single' underline_color='#98971a'"
printf "<span color='#b8bb26' background='#79740e' weight='bold'>%s</span>\n" "$OUTPUT"
