#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f "urxvt" -e pulsemixer ;;
	2) pamixer -t ;;
	4) pamixer --allow-boost -i 5 ;;
	5) pamixer --allow-boost -d 5 ;;
esac

ICON="󰝟"
VALUE="$(pamixer --get-volume)"
if [ "$VALUE" -gt "60" ]; then
	ICON="󰕾"
elif [ "$VALUE" -gt "30" ]; then
	ICON="󰖀"
elif [ "$VALUE" -gt "0" ]; then
	ICON="󰕿"
fi

OUTPUT="  $ICON $VALUE  "
[ "$(pamixer --get-mute)" = true ] && OUTPUT="  󰝟  "

# underline="underline='single' underline_color='#689d6a'"
printf "<span color='#8ec07c' background='#427b58' weight='bold'>%s</span>\n" "$OUTPUT"
