#!/bin/sh

DEFAULT_URLS_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/newsboat/urls"
[ -n "$URLS_FILE" ] || URLS_FILE="$DEFAULT_URLS_FILE"

notify() { notify-send -i newsboat -a ' newsboat' "$1"; }

unread_count() {
    unread="$(newsboat -u "$URLS_FILE" -x print-unread)"
    case $unread in
    [0-9]*) printf '%d' "${unread%% *}" ;;
    *) notify "$unread" ;;
    esac
}

update() {
    if pidof newsboat >/dev/null 2>&1; then
        return
    fi
    notify 'Updating RSS feeds...'
    old_unread="$(unread_count)"
    newsboat -u "$URLS_FILE" -x reload
    new_unread="$(unread_count)"

    new_entries_count=$((new_unread - old_unread))
    case $new_entries_count in
    0) notify 'No updates' ;;
    [1-9]*) notify "$new_entries_count new entries" ;;
    *) notify "Unexpected output '$new_entries_count'" ;;
    esac

}

case $BLOCK_BUTTON in
1) update ;;
esac

# shellcheck disable=SC2046
printf '%d' $(unread_count)
