#!/bin/sh

case $BLOCK_BUTTON in
1) setsid -f "${TERMINAL:-urxvt}" -e pulsemixer ;;
2) pamixer -t ;;
4) pamixer --allow-boost -i 5 ;;
5) pamixer --allow-boost -d 5 ;;
esac

ICON=󰝟
VALUE=$(pamixer --get-volume)
if [ "$VALUE" -gt 60 ]; then
    ICON=󰕾
elif [ "$VALUE" -gt 30 ]; then
    ICON=󰖀
elif [ "$VALUE" -gt 0 ]; then
    ICON=󰕿
fi

[ "$(pamixer --get-mute)" = true ] && OUTPUT=" 󰝟 " || OUTPUT=" $ICON ${VALUE}% "
printf '%s' "$OUTPUT"
